### ISSUE TITLE
nilfs-clean will not run if time() is < 0

### ISSUE THREAD

**Issue by ewheelerinc** [nilfs-dev/nilfs-utils#1]
For systems without realtime clocks, it is possible to boot a system which starts at EPOCH=0 of Jan 1, 1970.  If the time zone shifts your time negative, time() can return a negative value and report December of 1969.  

When nilfs-clean is run under these date constraints it fails to run the cleaning job and the disk fills up. The cleaner daemon does start, however.

For now my hack is to force a more modern date at boot time, however, it would be nice to see the cleaner daemon function even when the date is severely incorrect.

**Comment by konis** [comment]
I couldn't reproduce this issue on a test system with a negative time (December of 1969).
Did you remove files from the filesystem before running nilfs-clean to make them reclaimable ?

**Comment by konis** [comment]
v2.2.5 release includes improvements to make cleanerd/utils robust against system time changes.

Thanks
