### ISSUE TITLE
nilfs-related kernel crashes

### ISSUE THREAD

**Issue by mbb78** [nilfs-dev/nilfs-utils#16]
Hi!

I'm not sure if I'm posting this in the right place, but the crashes seem to be related with nilfs driver. I personally use Manjaro Linux. Some reports can be seen on the following posts:

[(https://forum.manjaro.org/t/stable-update-2019-11-14-kernels-plasma-kde-apps-kde-frameworks-mesa-nvidia/111239/134?u=mbb)](https://forum.manjaro.org/t/stable-update-2019-11-14-kernels-plasma-kde-apps-kde-frameworks-mesa-nvidia/111239/134?u=mbb)

[(https://forum.manjaro.org/t/kernel-bug-related-to-nilfs/112783?u=mbb)](https://forum.manjaro.org/t/kernel-bug-related-to-nilfs/112783?u=mbb)

To sumarize:
- this issue was first noted on kernel 4.14-154;
- the previous I was using (and still use) is 4.14.151;
- I don't know if the problem occurs between the two kernels above, because I may have skipped updates or Manjaro may not have issued them on the stable branch;
- so far I have tried kernels 4.14-154, 4.14-155, 4.19-85 and 5.3-12 (all of them fail);
- if I disable `pti` or `mitigations` with a kernel parameter the crash doesn't occur upon boot, but it eventually happens later, while using the nilfs partition (which I use for data);
- I use the kernel parameter `scsi_mod.use_blk_mq=1` but removing it doesn't change anything.

Thank you very much for reading this and for your work on the nilfs filesystem. I really like it. Please tell me if I should report the issue on the kernel bugtracker instead.

**Comment by konis** [comment]
This looks the same as following issue reported in mailing list:

- https://marc.info/?t=157413851100002
- https://marc.info/?l=linux-nilfs&m=157401249403466

Thank you for reporting details.

**Comment by mbb78** [comment]
Yes, it appears to be the same issue. Apparently the commit was identified, so I hope it gets fixed soon.

Thanks!

**Comment by daiyy** [comment]
A workaround could be disable CONFIG_CGROUP_WRITEBACK in your kernel config, rebuild kernel and reboot.

**Comment by mbb78** [comment]
Thank you. I will try this when I have time and report back.

**Comment by konis** [comment]
This issue was fixed by commit 8301c719a2bd ("nilfs2: fix null pointer dereference at 
nilfs_segctor_do_construct()") which is merged to kernel 5.8-rc1.
It was back ported to the following stable kernels:

v5.7.3  (linux-5.7.y)
v5.6.19 (linux-5.6.y)
v5.4.47 (linux-5.4.y)

For former stable kernels that back-ported the causal commit c3aab9a0bd91
("mm/filemap.c: don't initiate writeback if mapping has no dirty pages"), back porting
the above commit may resolve the issue.

**Comment by mbb78** [comment]
Thank you very much. I'm not currently using nilfs, but I'll get back to it.
