### ISSUE TITLE
Cannot remount on a NILFS2 RootFS

### ISSUE THREAD

**Issue by sisungo** [nilfs-dev/nilfs-utils#18]
Cannot remount a NILFS2 RootFS read-write after installing nilfs-utils, and it can be remounted read-write after removing /bin/mount.nilfs2. The error message is "resource busy".

**Comment by konis** [comment]
Can you share more information ?  (distro, kernel version, nilfs-utils version, etc)

**Comment by sisungo** [comment]
There is a same issue (void Linux, use musl live), I will close this issue.

**Comment by sisungo** [comment]
This is a same issue(voidlinux, musl, Linux-5.4, musllibc)
The remount command is:
mount.nilfs -o ro,remount $root

**Comment by sisungo** [comment]
This is a same issue(voidlinux, nilfs-utils 2.2.8, Linux-5.4, musllibc)
The remount command is:
mount.nilfs -o ro,remount $root
