### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [nilfs-dev/nilfs-utils#4]
Hello,
There is currently no way to verify the complete integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you

**Comment by konis** [comment]
Introduced PGP signature since v2.2.7.

Thanks

**Comment by omni6** [comment]
@konis 
great that you're back! Almost thout this project died. Best filesystem IMO, thank you!
