### ISSUE TITLE
Another shrinking issue

### ISSUE THREAD

**Issue by ikervagyok** [nilfs-dev/nilfs-utils#9]
Having a similar issue to https://github.com/nilfs-dev/nilfs-utils/issues/8. Shrinking starts like normal, but after some time it dies with `Error: operation failed during moving in-use segments: File exists` error. I repeatedly tried to reduce the filesystem size by a lesser amount, which sometimes makes this operation go longer before the error occurs.

The affected system is a microserver running a NILFS2 Storage Partition on top of a ~12TB RAID5 md-device. The OS is the latest NixOS unstable release, but the error was reproducible with different stable versions too (from 16.03 onwards). I also tried different Kernel versions (~4.4 - 4.10).

My original goal was to get down to ~9TB to be able to reshape my RAID, so i deleted all old snapshots and checkpoints. I have about 3TB free, so i should be able to reduce the partition size at least a bit.

The following output is my current try - I'll post when it's done with or without errors.

```
root ~ # nilfs-resize --verbose /dev/md127 11000G
Partition size = 12002361606144 bytes.
Shrink the filesystem size from 12002361606144 bytes to 11811160064000 bytes.
371178 free segments (3113666740224 bytes) will be left after shrinkage.
22793 segments will be truncated from segnum 1407999.
Do you wish to proceed (y/N)? y
Moving 8008 in-use segments.
progress |***--------------------------------------------|
```

**Comment by ikervagyok** [comment]
Well, of course it works after i report this:
```
root ~ # nilfs-resize --verbose /dev/md127 11000G
Partition size = 12002361606144 bytes.
Shrink the filesystem size from 12002361606144 bytes to 11811160064000 bytes.
371178 free segments (3113666740224 bytes) will be left after shrinkage.
22793 segments will be truncated from segnum 1407999.
Do you wish to proceed (y/N)? y
Moving 8008 in-use segments.
progress |***********************************************|
Truncating segments.
Done.
nilfs-resize --verbose /dev/md127 11000G  12.66s user 407.86s system 13% cpu 53:20.76 total
```

Going to try to reduce the disk-size in steps of 500GB, reporting as soon as it fails again.

**Comment by ikervagyok** [comment]
this is the output, when nilfs-resize fails:

```
root ~ # nilfs-resize --verbose /dev/md127 10500G 
Partition size = 12002361606144 bytes.
Shrink the filesystem size from 11811160064000 bytes to 11274289152000 bytes.
310333 free segments (2603261886464 bytes) will be left after shrinkage.
64000 segments will be truncated from segnum 1343999.
Do you wish to proceed (y/N)? y
Moving 39965 in-use segments.
progress |*********cannot clean segments: File exists----|

Error: operation failed during moving in-use segments: File exists
Aborted.
nilfs-resize --verbose /dev/md127 10500G  12.23s user 406.84s system 15% cpu 44:43.84 total
```

**Comment by konis** [comment]
This bug "File exists (EEXIST) error" was probably fixed by the commit titled
"nilfs-utils: Fix conflicting data buffer error":
- commit 2146d604540e146efa2faa9c6f7784f7cfb14972 for master branch, 
- commit ef281d5458c68eee8d9b572124d7841dddf0acd7 for v2.2.y branch

The fix is available by nilfs-utils 2.2.7 or the latest master branch. 
Will close for now.

Thanks

**Comment by ikervagyok** [comment]
Thanks, can't check though, as the affected filesystem doesn't exist anymore.

**Comment by spiffytech** [comment]
I encountered this issue with nilfs-utils 2.2.1, and using the latest version from git fixed the issue.
